version: '2'

services:
  web:
    build: .
    command: apache2-foreground
    environment:
      - SSL_TERMINATION=1
      - LD_LIBRARY_PATH=/opt/miniconda3/lib
    ports:
      - "8000:8080"
    user: 62983:62983
    cap_drop:
      - ALL
