version: '2'

services:
  web:
    build: .
    ports:
      - "8765:8080"

  crystaltoolkit:
      build:
          context: crystaltoolkit
      depends_on:
          - kv
          - web

  kv:
    image: redis:5.0.3
