version: '2'

services:
  web:
    build: .
    restart: always
    #volumes:
    #- web.mp-web:/var/log/apache2    
    cap_drop:
      - ALL
    cap_add:
    - CHOWN
    - DAC_OVERRIDE
    - FOWNER
    - SETGID
    - SETUID
