version: '2'

services:
  web:
    build: .
    command: filebeat -e
    user: 62983:62983
    stdin_open: true
    tty: true
    volumes:
      - web.mp-web:/var/log/apache2
    cap_drop:
      - ALL
    cap_add:
    - CHOWN
